// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ToDoAPI.Specs.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class HanteraTodosFeature : object, Xunit.IClassFixture<HanteraTodosFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("sv"), "Features", "Hantera todos", "  Som användare vill jag kunna klarmarkera, ta bort och redigera mina todos så mi" +
                "n lista på uppgifter är aktuell", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "HanteraTodo.feature"
#line hidden
        
        public HanteraTodosFeature(HanteraTodosFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Markera en todo som klar")]
        [Xunit.TraitAttribute("FeatureTitle", "Hantera todos")]
        [Xunit.TraitAttribute("Description", "Markera en todo som klar")]
        public async System.Threading.Tasks.Task MarkeraEnTodoSomKlar()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Markera en todo som klar", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("att todo-listan innehåller en todo med titeln \"Handla mjölk\" som inte är klar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Givet ");
#line hidden
#line 8
 await testRunner.WhenAsync("jag markerar todo:n \"Handla mjölk\" som klar", ((string)(null)), ((global::Reqnroll.Table)(null)), "När ");
#line hidden
#line 9
 await testRunner.ThenAsync("ska todo:n \"Handla mjölk\" vara markerad som klar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Så ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ta bort en todo")]
        [Xunit.TraitAttribute("FeatureTitle", "Hantera todos")]
        [Xunit.TraitAttribute("Description", "Ta bort en todo")]
        public async System.Threading.Tasks.Task TaBortEnTodo()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ta bort en todo", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
 await testRunner.GivenAsync("att todo-listan innehåller en todo med titeln \"Handla mjölk\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Givet ");
#line hidden
#line 13
 await testRunner.WhenAsync("jag tar bort todo:n \"Handla mjölk\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "När ");
#line hidden
#line 14
 await testRunner.ThenAsync("ska todo-listan vara tom", ((string)(null)), ((global::Reqnroll.Table)(null)), "Så ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Redigera en todo")]
        [Xunit.TraitAttribute("FeatureTitle", "Hantera todos")]
        [Xunit.TraitAttribute("Description", "Redigera en todo")]
        public async System.Threading.Tasks.Task RedigeraEnTodo()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Redigera en todo", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
    await testRunner.GivenAsync("att todo-listan innehåller en todo med titeln \"Handla mjölk\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Givet ");
#line hidden
#line 18
    await testRunner.WhenAsync("jag redigerar todo:n \"Handla mjölk\" och ändrar titeln till \"Köpa mjölk\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "När ");
#line hidden
#line 19
    await testRunner.ThenAsync("ska todo-listan innehålla en todo med titeln \"Köpa mjölk\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Så ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Försöka redigera en todo alla egenskaper")]
        [Xunit.TraitAttribute("FeatureTitle", "Hantera todos")]
        [Xunit.TraitAttribute("Description", "Försöka redigera en todo alla egenskaper")]
        public async System.Threading.Tasks.Task ForsokaRedigeraEnTodoAllaEgenskaper()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Försöka redigera en todo alla egenskaper", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
    await testRunner.GivenAsync("att todo-listan innehåller en todo med titeln \"Handla mjölk\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Givet ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "titel",
                            "beskrivning",
                            "förfallodatum"});
                table1.AddRow(new string[] {
                            "\"Köpa mjölk\"",
                            "\"Köp mjölk från affären\"",
                            "\"2025-10-01\""});
#line 23
    await testRunner.WhenAsync("jag försöker redigera todo:n \"Handla mjölk\" och ändrar alla egenskaper", ((string)(null)), table1, "När ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "titel",
                            "beskrivning",
                            "förfallodatum"});
                table2.AddRow(new string[] {
                            "\"Köpa mjölk\"",
                            "\"Köp mjölk från affären\"",
                            "\"2025-10-01\""});
#line 26
    await testRunner.ThenAsync("ska todo-listan innehålla en todo med", ((string)(null)), table2, "Så ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Försöka ange en tom titel vid redigering")]
        [Xunit.TraitAttribute("FeatureTitle", "Hantera todos")]
        [Xunit.TraitAttribute("Description", "Försöka ange en tom titel vid redigering")]
        public async System.Threading.Tasks.Task ForsokaAngeEnTomTitelVidRedigering()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Försöka ange en tom titel vid redigering", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
    await testRunner.GivenAsync("att todo-listan innehåller en todo med titeln \"Handla mjölk\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Givet ");
#line hidden
#line 32
    await testRunner.WhenAsync("jag försöker redigera todo:n \"Handla mjölk\" och anger en tom titel", ((string)(null)), ((global::Reqnroll.Table)(null)), "När ");
#line hidden
#line 33
    await testRunner.ThenAsync("ska jag få felmeddelandet \"Titeln kan inte vara tom\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Så ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Försöka ange ett felaktigt datumformat vid redigering")]
        [Xunit.TraitAttribute("FeatureTitle", "Hantera todos")]
        [Xunit.TraitAttribute("Description", "Försöka ange ett felaktigt datumformat vid redigering")]
        [Xunit.InlineDataAttribute("\"2023-31-12\"", new string[0])]
        [Xunit.InlineDataAttribute("\"2023-02-30\"", new string[0])]
        [Xunit.InlineDataAttribute("\"2023-13-01\"", new string[0])]
        public async System.Threading.Tasks.Task ForsokaAngeEttFelaktigtDatumformatVidRedigering(string datum, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("datum", datum);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Försöka ange ett felaktigt datumformat vid redigering", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 36
    await testRunner.GivenAsync("att todo-listan innehåller en todo med titeln \"Handla mjölk\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Givet ");
#line hidden
#line 37
    await testRunner.WhenAsync(string.Format("jag försöker redigera todo:n \"Handla mjölk\" och anger ett datumformat {0}", datum), ((string)(null)), ((global::Reqnroll.Table)(null)), "När ");
#line hidden
#line 38
    await testRunner.ThenAsync("ska jag få felmeddelandet \"Datumformatet är ogiltigt\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Så ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await HanteraTodosFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await HanteraTodosFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
