// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ToDoAPI.Specs.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SkapaTodosFeature : object, Xunit.IClassFixture<SkapaTodosFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("sv"), "Features", "Skapa todos", "  Som användare vill jag kunna skapa mina todos så att jag kan hålla koll på vad " +
                "som ska göras", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SkapaTodo.feature"
#line hidden
        
        public SkapaTodosFeature(SkapaTodosFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Visa tom todo-lista")]
        [Xunit.TraitAttribute("FeatureTitle", "Skapa todos")]
        [Xunit.TraitAttribute("Description", "Visa tom todo-lista")]
        public async System.Threading.Tasks.Task VisaTomTodo_Lista()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Visa tom todo-lista", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 10
 await testRunner.WhenAsync("jag öppnar todo-appen", ((string)(null)), ((global::Reqnroll.Table)(null)), "När ");
#line hidden
#line 11
 await testRunner.ThenAsync("ska jag se att listan är tom", ((string)(null)), ((global::Reqnroll.Table)(null)), "Så ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Lägga till en ny todo")]
        [Xunit.TraitAttribute("FeatureTitle", "Skapa todos")]
        [Xunit.TraitAttribute("Description", "Lägga till en ny todo")]
        public async System.Threading.Tasks.Task LaggaTillEnNyTodo()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Lägga till en ny todo", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 14
 await testRunner.WhenAsync("jag lägger till en ny todo med titeln \"Handla mjölk\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "När ");
#line hidden
#line 15
 await testRunner.ThenAsync("ska todo-listan innehålla en todo med titeln \"Handla mjölk\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Så ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Lägga till en ny todo med exempel")]
        [Xunit.TraitAttribute("FeatureTitle", "Skapa todos")]
        [Xunit.TraitAttribute("Description", "Lägga till en ny todo med exempel")]
        [Xunit.InlineDataAttribute("\"Handla mjölk\"", new string[0])]
        [Xunit.InlineDataAttribute("\"Laga mat\"", new string[0])]
        [Xunit.InlineDataAttribute("\"Städa\"", new string[0])]
        public async System.Threading.Tasks.Task LaggaTillEnNyTodoMedExempel(string titel, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("titel", titel);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Lägga till en ny todo med exempel", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 18
 await testRunner.WhenAsync(string.Format("jag lägger till en ny todo med titeln {0}", titel), ((string)(null)), ((global::Reqnroll.Table)(null)), "När ");
#line hidden
#line 19
 await testRunner.ThenAsync(string.Format("ska todo-listan innehålla en todo med titeln {0}", titel), ((string)(null)), ((global::Reqnroll.Table)(null)), "Så ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Lägga till flera todos")]
        [Xunit.TraitAttribute("FeatureTitle", "Skapa todos")]
        [Xunit.TraitAttribute("Description", "Lägga till flera todos")]
        public async System.Threading.Tasks.Task LaggaTillFleraTodos()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Lägga till flera todos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "titel"});
                table3.AddRow(new string[] {
                            "Handla mjölk"});
                table3.AddRow(new string[] {
                            "Laga mat"});
                table3.AddRow(new string[] {
                            "Städa"});
#line 28
 await testRunner.WhenAsync("jag lägger till följande todos", ((string)(null)), table3, "När ");
#line hidden
#line 33
 await testRunner.ThenAsync("ska todo-listan innehålla 3 todos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Så ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Lägga till en todo med detaljer")]
        [Xunit.TraitAttribute("FeatureTitle", "Skapa todos")]
        [Xunit.TraitAttribute("Description", "Lägga till en todo med detaljer")]
        public async System.Threading.Tasks.Task LaggaTillEnTodoMedDetaljer()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Lägga till en todo med detaljer", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 36
 await testRunner.WhenAsync("jag lägger till en ny todo med titeln \"Handla mjölk\", beskrivningen \"Köp mjölk fr" +
                        "ån affären\" och förfallodatumet \"2025-10-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "När ");
#line hidden
#line 37
 await testRunner.ThenAsync("ska todo-listan innehålla en todo med titeln \"Handla mjölk\", beskrivningen \"Köp m" +
                        "jölk från affären\" och förfallodatumet \"2025-10-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Så ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Lägga till en todo med detaljer (enklare att läsa)")]
        [Xunit.TraitAttribute("FeatureTitle", "Skapa todos")]
        [Xunit.TraitAttribute("Description", "Lägga till en todo med detaljer (enklare att läsa)")]
        public async System.Threading.Tasks.Task LaggaTillEnTodoMedDetaljerEnklareAttLasa()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Lägga till en todo med detaljer (enklare att läsa)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "titel",
                            "beskrivning",
                            "förfallodatum"});
                table4.AddRow(new string[] {
                            "Handla mjölk",
                            "Köp mjölk från affären",
                            "2025-10-01"});
#line 40
 await testRunner.WhenAsync("jag lägger till en ny todo med", ((string)(null)), table4, "När ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "titel",
                            "beskrivning",
                            "förfallodatum"});
                table5.AddRow(new string[] {
                            "Handla mjölk",
                            "Köp mjölk från affären",
                            "2025-10-01"});
#line 43
 await testRunner.ThenAsync("ska todo-listan innehålla en todo med", ((string)(null)), table5, "Så ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Lägga till en todo med passerat datum")]
        [Xunit.TraitAttribute("FeatureTitle", "Skapa todos")]
        [Xunit.TraitAttribute("Description", "Lägga till en todo med passerat datum")]
        public async System.Threading.Tasks.Task LaggaTillEnTodoMedPasseratDatum()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Lägga till en todo med passerat datum", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 48
 await testRunner.WhenAsync("jag lägger till en ny todo med titeln \"Handla mjölk\", beskrivningen \"Köp mjölk fr" +
                        "ån affären\" och förfallodatumet \"2022-01-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "När ");
#line hidden
#line 49
 await testRunner.ThenAsync("ska jag få felmeddelandet \"Förfallodatumet kan inte vara i det förflutna\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Så ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Lägga till en todo med felaktigt datumformat")]
        [Xunit.TraitAttribute("FeatureTitle", "Skapa todos")]
        [Xunit.TraitAttribute("Description", "Lägga till en todo med felaktigt datumformat")]
        public async System.Threading.Tasks.Task LaggaTillEnTodoMedFelaktigtDatumformat()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Lägga till en todo med felaktigt datumformat", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 51
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 52
 await testRunner.WhenAsync("jag lägger till en ny todo med titeln \"Handla mjölk\", beskrivningen \"Köp mjölk fr" +
                        "ån affären\" och förfallodatumet \"2023-31-12\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "När ");
#line hidden
#line 53
 await testRunner.ThenAsync("ska jag få felmeddelandet \"Datumformatet är ogiltigt\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Så ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SkapaTodosFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await SkapaTodosFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
